-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.profiles (
  id uuid NOT NULL,
  updated_at timestamp with time zone,
  username text UNIQUE CHECK (char_length(username) >= 3),
  full_name text,
  avatar_url text,
  website text,
  resume_id uuid,
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id),
  CONSTRAINT profiles_resume_id_fkey FOREIGN KEY (resume_id) REFERENCES public.resumes(id)
);
CREATE TABLE public.resume_creation_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  session_id text NOT NULL,
  event_type text NOT NULL CHECK (event_type = ANY (ARRAY['page_view'::text, 'step_change'::text, 'step_duration'::text, 'template_selection'::text, 'theme_selection'::text, 'save_attempt'::text, 'session_end'::text])),
  event_timestamp timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  step_number integer CHECK (step_number >= 0 AND step_number <= 10),
  step_name text,
  time_spent_on_step integer CHECK (time_spent_on_step >= 0),
  template_id text,
  theme_id text,
  save_success boolean,
  save_error_message text,
  page_url text,
  CONSTRAINT resume_creation_events_pkey PRIMARY KEY (id),
  CONSTRAINT resume_creation_events_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.resume_creation_sessions(session_id)
);
CREATE TABLE public.resume_creation_sessions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  session_id text NOT NULL UNIQUE,
  user_id uuid,
  is_first_time_visitor boolean NOT NULL DEFAULT false,
  user_agent text,
  ip_address inet,
  country text,
  city text,
  region text,
  referrer text,
  session_started_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  session_ended_at timestamp with time zone,
  total_session_duration integer,
  completed boolean DEFAULT false,
  final_step_reached integer,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT resume_creation_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT resume_creation_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.resume_interactions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  resume_id uuid NOT NULL,
  view_id uuid NOT NULL,
  interaction_type text NOT NULL,
  target_value text,
  section_name text,
  clicked_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  session_id text,
  country text,
  city text,
  region text,
  latitude numeric,
  longitude numeric,
  CONSTRAINT resume_interactions_pkey PRIMARY KEY (id),
  CONSTRAINT resume_interactions_view_id_fkey FOREIGN KEY (view_id) REFERENCES public.resume_views(id),
  CONSTRAINT resume_interactions_resume_id_fkey FOREIGN KEY (resume_id) REFERENCES public.resumes(id)
);
CREATE TABLE public.resume_views (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  resume_id uuid NOT NULL,
  session_id text NOT NULL,
  ip_address inet,
  user_agent text,
  country text,
  city text,
  region text,
  latitude numeric,
  longitude numeric,
  referrer text,
  view_duration integer DEFAULT 0,
  viewed_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT resume_views_pkey PRIMARY KEY (id),
  CONSTRAINT resume_views_resume_id_fkey FOREIGN KEY (resume_id) REFERENCES public.resumes(id)
);
CREATE TABLE public.resumes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text NOT NULL,
  template_id text NOT NULL,
  is_public boolean DEFAULT true,
  personal_info jsonb,
  experience jsonb,
  education jsonb,
  skills jsonb,
  projects jsonb,
  certifications jsonb,
  languages jsonb,
  custom_sections jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  slug text NOT NULL UNIQUE,
  theme_id text NOT NULL DEFAULT 'black'::text,
  view_count integer NOT NULL DEFAULT 0,
  user_id uuid,
  uploaded_file_path text,
  uploaded_file_url text,
  original_filename text,
  file_size_bytes bigint,
  mime_type text,
  uploaded_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  uploaded_file_id uuid,
  CONSTRAINT resumes_pkey PRIMARY KEY (id),
  CONSTRAINT resumes_uploaded_file_id_fkey FOREIGN KEY (uploaded_file_id) REFERENCES public.uploaded_resume_files(id),
  CONSTRAINT resumes_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.uploaded_resume_files (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  file_path text NOT NULL UNIQUE,
  file_url text,
  original_filename text NOT NULL,
  file_size_bytes bigint NOT NULL,
  mime_type text NOT NULL,
  parsed_data jsonb,
  is_used boolean DEFAULT false,
  associated_resume_id uuid,
  uploaded_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  last_accessed_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  deleted_at timestamp with time zone,
  CONSTRAINT uploaded_resume_files_pkey PRIMARY KEY (id),
  CONSTRAINT uploaded_resume_files_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT uploaded_resume_files_associated_resume_id_fkey FOREIGN KEY (associated_resume_id) REFERENCES public.resumes(id)
);